Repository mango-habanero/mango-habanero-be, pull requests merged in 2024-04, with the labels that each got.

#8 Integrate Ruff and Mypy for enhanced code quality.
  poetry.lock
  pyproject.toml
Labels: feature

#9 Infrastructure setup: CI/CD Integration, CLI tools, containerization, and more.
  .dockerignore
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  Dockerfile
  app/__init__.py
  app/cli.py
  app/exceptions.py
  app/main.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: feature

#11 Integrate depandabot.
  .github/dependabot.yml
Labels: feature

#12 Implement Granian server and enhanced performance.
  Dockerfile
  app/cli.py
  poetry.lock
  pyproject.toml
Labels: feature, Fast API

#15 Enhance CI/CD workflow with composite actions, alpine base Image, and improved tagging.
  .github/actions/python.yml
  .github/workflows/ci.yml
  Dockerfile
  pyproject.toml
Labels: feature, enhancement

#18 Enhance logging, refactor project structure, and update development settings.
  Dockerfile
  poetry.lock
  pyproject.toml
  src/__init__.py
  src/app.py
  src/cli.py
  src/config/log.py
  src/exceptions.py
  src/main.py
  src/middleware/requests.py
Labels: feature

#19 Integrate mango-habanero-bot for automated bypass of protection ruleset.
  .github/workflows/ci.yml
Labels: enhancement
